# Generated by Django 3.0.3 on 2020-02-11 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0003_auto_20200211_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='title_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
